
/* Drop Tables */

DROP TABLE IF EXISTS WIN_TABLE;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS MACHINE;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS PROJECT;




/* Create Tables */

CREATE TABLE EVENT
(
	EVENT_ID INT NOT NULL,
	PROJECT_ID VARCHAR(32) NOT NULL,
	EVENT_TIME TIMESTAMP,
	M_ID VARCHAR(128),
	MEMO TEXT,
	PRIMARY KEY (EVENT_ID, PROJECT_ID),
	CONSTRAINT EVENT_KEY UNIQUE (EVENT_ID, PROJECT_ID)
) WITHOUT OIDS;


CREATE TABLE MACHINE
(
	M_ID VARCHAR(128) NOT NULL,
	PROJECT_ID VARCHAR(32) NOT NULL,
	PLACE_ID INT NOT NULL,
	MEMO TEXT,
	PRIMARY KEY (M_ID, PROJECT_ID),
	CONSTRAINT MACHINE_KEY UNIQUE (M_ID, PROJECT_ID)
) WITHOUT OIDS;


CREATE TABLE PLACE
(
	PLACE_ID INT NOT NULL,
	LATITUDE TEXT,
	LONGITUDE TEXT,
	ADDRESS TEXT,
	MEMO TEXT,
	PRIMARY KEY (PLACE_ID)
) WITHOUT OIDS;


CREATE TABLE PROJECT
(
	PROJECT_ID VARCHAR(32) NOT NULL,
	PROJECT_NAME VARCHAR(128),
	PRIMARY KEY (PROJECT_ID)
) WITHOUT OIDS;


CREATE TABLE WIN_TABLE
(
	WIN_FILE_NAMEID CHAR(20) NOT NULL,
	EVENT_ID INT NOT NULL,
	PROJECT_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (WIN_FILE_NAMEID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE WIN_TABLE
	ADD FOREIGN KEY (EVENT_ID, PROJECT_ID)
	REFERENCES EVENT (EVENT_ID, PROJECT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EVENT
	ADD FOREIGN KEY (PROJECT_ID, M_ID)
	REFERENCES MACHINE (PROJECT_ID, M_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MACHINE
	ADD FOREIGN KEY (PLACE_ID)
	REFERENCES PLACE (PLACE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



